### ISSUE TITLE
Doubt wrt class balancing in ERFNet and its effect

### ISSUE THREAD

**Issue by prachigarg23** [ifnspaml/CIL_Segmentation#6]
Hi, the original ERFNet Pytorch code https://github.com/Eromera/erfnet_pytorch calculated weights for class balancing by processing dataset histograms (as are specified for cityscapes in their code under train/main.py lines 88-133). As I understand, no class balancing has been used in your training code. Is this true for the model-based baselines and SS, single stage trainings in your paper? If so is there any specific reason for that? Can you please give some idea on how much difference using/not using class balancing would make to ERFNet training?

**Comment by klingner** [comment]
Hi, thank you for bringing up this detail. You are absolutely right that the original ERFNet-Code uses class-balancing weights. In contrast, we did not use any weights for all baselines and also not for the single-stage training. The reason is that we noted that using the weights also weighs the old task against the new task, which turned out to lead to infavorable behaviour when extending the model to more classes. Using the original class-balancing weights would improve the single-stage model by about 5 points in mIoU (compare with the original paper) but leads to decreased performance for all incremental learning methods.
